server:
  port: 80
spring:
  application:
    name: api-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.200.128:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: service-product
          uri: lb://service-product
          predicates:
            - Path=/**/product/**
        - id: service-user
          uri: lb://service-user
          predicates:
            - Path=/**/user/**
        - id: service-oauth
          uri: lb://service-oauth
          predicates:
              - Path=/**/login/**
  redis:
    host: 192.168.200.128
    port: 6379
